CREATE TABLE IF NOT EXISTS user_communities (
  user_id INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  community_id INT NOT NULL REFERENCES communities (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, community_id)
);